version: '3.9'

services:
    datastore:
      image: postgres:13.4-alpine
      container_name: postgres
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_DB=wdi_worldbank
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      volumes:
        - './datastore/init:/docker-entrypoint-initdb.d/'
        - './datastore/processed:/data/'
  
    api:
      container_name: flask-api
      restart: always
      build:
        context: ./api
        dockerfile: Dockerfile
      ports:
        - "5000:80"
      volumes:
        - ./api:/usr/src/app
      depends_on:
        - "datastore"
  
    frontend:
      container_name: react-app
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - '3000:3000'
      depends_on:
        - "api"